export const data = [{
    name: 'test',
    description: 'Description'
}, {
    name: 'test',
    description: 'Description'
}, {
    name: 'test',
    description: 'Description'
}, {
    name: 'test',
    description: 'Description'
}, {
    name: 'test',
    description: 'Description'
}, {
    name: 'test',
    description: 'Description'
}, {
    name: 'test',
    description: 'Description'
}, {
    name: 'test',
    description: 'Description'
}, {
    name: 'test',
    description: 'Description'
}, {
    name: 'test',
    description: 'Description'
}, {
    name: 'test',
    description: 'Description'
}, {
    name: 'test',
    description: 'Description'
}, {
    name: 'test',
    description: 'Description'
}, {
    name: 'test',
    description: 'Description'
}, {
    name: 'test',
    description: 'Description'
}, {
    name: 'test',
    description: 'Description'
}, {
    name: 'test',
    description: 'Description'
}, {
    name: 'test',
    description: 'Description'
}, {
    name: 'test',
    description: 'Description'
}];
